name: Build Enigma Core
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.ref_name }}

    steps:
      - name: Checkout this MicroPython repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git jq wget 
      
      - name: Install MicroPython
        uses: BrianPugh/install-micropython@v2

      - name: Compile firmware
        run: |
          ./build.sh
      
      - name: Create release archive
        run: |
          cd dist
          zip -r "enigma-core-v${{ env.VERSION }}.zip" .

      - name: Create Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Enigma Core version ${VERSION}
          files: enigma-core-${{ env.VERSION }}.zip